sudo: false

cache: yarn

language: node_js

env:
  global:
  - NODE_ENV='test'
  - DOCKER_USERNAME='piglesias_gmv+travis_ci'
  - DOCKER_PASSWORD='TINK8VO9AS0RIUEM822CP53XY3R5E0R163G19CA729YZR7BLG9QQQ6G9073SSCCF'

before_install:
 - cd ./$SERVICE
 - nvm install
 - nvm use
 - npm install --only=production

before_script:
  - SERVICE=$SERVICE make ensure-dependencies
  - sleep 10

script:
  - make brand
  - make package
  - make qa

matrix:
  include:
  - env: SERVICE=recipes-api
    services:
    - docker
  - env: SERVICE=recipes-crawler
    services:
    - docker
  - env: SERVICE=recipes-id-generator
    services:
    - docker